accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^games/$', views.games, name='games'),
    url(r'^games/add/$', 'lists.views.add_game', name='add_game'),
    url(r'^games/remove/$', 'lists.views.remove_game', name='remove_game'),
    url(r'^games/recommended/$', 'lists.views.recommended_games', name='recommended_games'),
    url(r'^games/import/steam/$', 'lists.views.import_steam_games', name='import_steam_games'),
    url(r'^games/import/xbox/$', 'lists.views.import_xbox_games', name='import_xbox_games'),
    url(r'^friends/$', views.friends, name='friends'),
    url(r'^friends/request/$', 'friends.views.friend_request_send', name='request_friend'),
    url(r'^friends/accept/$', 'friends.views.friend_request_accept', name='accept_friend'),
    url(r'^friends/reject/$', 'friends.views.friend_request_reject', name='reject_friend'),
    url(r'^friends/remove/$', 'friends.views.friend_remove', name='remove_friend'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/games$', views.search_friends_games, name="game_search"),
)

game_atlas/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'game_atlas.views.home', name='home'),
    # url(r'^game_atlas/', include('game_atlas.foo.urls')),

    url(r'^$', 'games.views.index', name='home'),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('users.urls', namespace='users')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

games/urls.py
from django.conf.urls import patterns, url

from games import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^releases/$', views.releases, name='releases'),
    url(r'^add/$', views.game_add, name='game_add'),
    url(r'^import/$', views.game_import, name='game_import'),
    url(r'^delete/$', views.game_delete, name='game_delete'),
    url(r'^search/$', views.game_search, name='game_search'),
    url(r'^(?P<game_id>\d+)/$', views.game_detail, name='game_detail'),
    url(r'^(?P<game_id>\d+)/edit/$', views.game_edit, name='game_edit'),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^(?P<username>[\w.@+-]+)/$', views.profile, name='profile'),
    url(r'^(?P<username>[\w.@+-]+)/games/$', views.games, name='games'),
    url(r'^(?P<username>[\w.@+-]+)/friends/$', views.friends, name='friends'),
)

game_atlas/utils/models.py
def dict_fetch_all(cursor):
    """Return all rows from a cursor as a dict"""
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def dict_fetch_one(cursor):
    """Return one row from a cursor as a dict"""
    row = cursor.fetchone()
    if not row:
        return {}
    return dict(zip((col[0] for col in cursor.description), row))

game_atlas/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Game Atlas{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <style>
    body {
      padding-top: 60px;
    }
  </style>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="{% url 'home' %}">Game Atlas</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><a href="{% url 'games:index' %}">Games</a></li>
            <li><a href="{% url 'games:releases' %}">Releases</a></li>
            <li><a href="{% url 'games:game_search' %}">Search</a></li>
            <li><a href="{% url 'accounts:search' %}">Users</a></li>
          </ul>
          <ul class="nav pull-right">
            {% if user.is_authenticated %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {{ user.username }} <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'accounts:profile' %}">Profile</a></li>
                <li><a href="{% url 'accounts:friends' %}">Friends</a></li>
                <li><a href="{% url 'accounts:games' %}">My Games</a></li>
                <li><a href="{% url 'accounts:recommended_games' %}">Recommended</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
              </ul>
            </li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <script src="{% static "js/jquery-1.9.1.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>