accounts/urls.py
from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^games/$', views.games, name='games'),
    url(r'^games/add/$', 'lists.views.add_game', name='add_game'),
    url(r'^games/remove/$', 'lists.views.remove_game', name='remove_game'),
    url(r'^games/recommended/$', 'lists.views.recommended_games', name='recommended_games'),
    url(r'^games/import/steam/$', 'lists.views.import_steam_games', name='import_steam_games'),
    url(r'^games/import/xbox/$', 'lists.views.import_xbox_games', name='import_xbox_games'),
    url(r'^friends/$', views.friends, name='friends'),
    url(r'^friends/request/$', 'friends.views.friend_request_send', name='request_friend'),
    url(r'^friends/accept/$', 'friends.views.friend_request_accept', name='accept_friend'),
    url(r'^friends/reject/$', 'friends.views.friend_request_reject', name='reject_friend'),
    url(r'^friends/remove/$', 'friends.views.friend_remove', name='remove_friend'),
    url(r'^search/$', views.search, name='search'),
    url(r'^search/games$', views.search_friends_games, name="game_search"),
)

game_atlas/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'game_atlas.views.home', name='home'),
    # url(r'^game_atlas/', include('game_atlas.foo.urls')),

    url(r'^$', 'games.views.index', name='home'),
    url(r'^games/', include('games.urls', namespace='games')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^users/', include('users.urls', namespace='users')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

games/urls.py
from django.conf.urls import patterns, url

from games import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^releases/$', views.releases, name='releases'),
    url(r'^add/$', views.game_add, name='game_add'),
    url(r'^import/$', views.game_import, name='game_import'),
    url(r'^delete/$', views.game_delete, name='game_delete'),
    url(r'^search/$', views.game_search, name='game_search'),
    url(r'^(?P<game_id>\d+)/$', views.game_detail, name='game_detail'),
    url(r'^(?P<game_id>\d+)/edit/$', views.game_edit, name='game_edit'),
)

games/models.py
from django.db import models, connection, transaction

from game_atlas.utils.models import dict_fetch_all, dict_fetch_one

class Genre(models.Model):

    class Meta:
        managed = False
        db_table = 'genre'

    @staticmethod
    def select_all():
        cursor = connection.cursor()

        query = 'SELECT id, name FROM genre'
        cursor.execute(query)

        return dict_fetch_all(cursor)

    @staticmethod
    def add_genre(genre):
        cursor = connection.cursor()

        query = 'INSERT INTO genre (name) VALUES (%s) RETURNING id'
        cursor.execute(query, (genre,))
        transaction.commit_unless_managed()

        row = cursor.fetchone()

        if not row:
            return None
        return row[0]

    @staticmethod
    def get_genre_id(genre):
        cursor = connection.cursor()

        query = 'SELECT id FROM genre WHERE name = %s'
        cursor.execute(query, (genre,))

        row = cursor.fetchone()
        if not row:
            return Genre.add_genre(genre)
        else:
            return row[0]

class Game(models.Model):

    class Meta:
        managed = False
        db_table = 'game'

    @staticmethod
    def select_all():
        cursor = connection.cursor()

        query = """
            SELECT game.id, game.title, genre.name as "genre_name"
            FROM game JOIN genre ON game.genre_id=genre.id ORDER BY game.title
        """
        cursor.execute(query)

        return dict_fetch_all(cursor)

    @staticmethod
    def select(game_id):
        cursor = connection.cursor()

        query = """
            SELECT game.id, title, genre_id, genre.name as "genre_name"
            FROM game JOIN genre ON game.genre_id=genre.id
            WHERE game.id = %s
        """
        cursor.execute(query, (game_id,))

        return dict_fetch_one(cursor)

    @staticmethod
    def select_many(game_ids):
        cursor = connection.cursor()

        query = """
            SELECT game.id, title, genre_id, genre.name as "genre_name"
            FROM game JOIN genre ON game.genre_id=genre.id
            WHERE game.id = ANY(%s)
        """
        cursor.execute(query, (game_ids,))

        return dict_fetch_all(cursor)

    @staticmethod
    def select_many_by_title(titles):
        cursor = connection.cursor()

        query = """
            SELECT id, title FROM game
            WHERE title = ANY(%s)
        """
        cursor.execute(query, (titles,))

        return dict_fetch_all(cursor)

    @staticmethod
    def insert(title, genre_id):
        cursor = connection.cursor()

        query = 'INSERT INTO game (title, genre_id) VALUES (%s, %s) RETURNING id'
        cursor.execute(query, (title, genre_id))
        transaction.commit_unless_managed()

        row = cursor.fetchone()
        if not row:
            return None
        return row[0]

    #Used to check to make sure we aren't adding a game that is already in the db
    @staticmethod
    def add_game(title, genre_id):
        cursor = connection.cursor()

        query = """
                    SELECT game.id, title FROM game
                    INNER JOIN genre ON game.genre_id = genre.id
                    WHERE game.title = %s AND genre.id = %s
                """
        cursor.execute(query, (title, genre_id,))

        row = cursor.fetchone()
        if row is None:
            return Game.insert(title, genre_id)
        return row[0]

    @staticmethod
    def update(game_id, title, genre_id):
        cursor = connection.cursor()

        query = 'UPDATE game SET title=%s, genre_id=%s WHERE id = %s'
        cursor.execute(query, (title, genre_id, game_id))
        transaction.commit_unless_managed()

    @staticmethod
    def delete(game_id):
        cursor = connection.cursor()

        query = 'DELETE FROM game WHERE id = %s'
        cursor.execute(query, (game_id,))
        transaction.commit_unless_managed()

    @staticmethod
    def find(title):
        cursor = connection.cursor()
        search= "%" + title + "%"
        query = 'SELECT id, title FROM game WHERE title ILIKE %s'
        cursor.execute(query, (search,))

        return dict_fetch_all(cursor)

    @staticmethod
    def game_detail(game_id):
        cursor = connection.cursor()

        query = """
                SELECT game.title, release.release_date, 
                genre.name AS "genre_name", platform.name as "platform_name"
                FROM release
                JOIN game on release.game_id = game.id
                JOIN platform on release.platform_id = platform.id
                JOIN genre ON game.genre_id = genre.id
                WHERE game.id = %s
            """ 

        cursor.execute(query, (game_id,))

        return dict_fetch_all(cursor)

class Platform(models.Model):

    class Meta:
        managed = False
        db_table = 'platform'

    @staticmethod
    def get_platform_id(platform):
        cursor = connection.cursor()

        query = 'SELECT id FROM platform WHERE name = %s'
        cursor.execute(query, (platform,))

        row = cursor.fetchone()
        if not row:
            return Platform.add_platform(platform)
        else:
            return row[0]

    @staticmethod
    def add_platform(platform):
        cursor = connection.cursor()

        query = 'INSERT INTO platform (name) VALUES (%s) RETURNING id'
        cursor.execute(query, (platform,))
        transaction.commit_unless_managed()

        row = cursor.fetchone()

        if not row:
            return None
        return row[0]

class Release(models.Model):

    class Meta:
        managed = False
        db_table = 'release'

    @staticmethod
    def select_all():
        cursor = connection.cursor()

        query = """
            SELECT game.title, release.release_date,
            genre.name as "genre_name", platform.name as "platform_name"
            FROM release
            JOIN game ON release.game_id=game.id
            JOIN platform ON release.platform_id=platform.id
            JOIN genre ON game.genre_id=genre.id
        """
        cursor.execute(query)

        return dict_fetch_all(cursor)

    @staticmethod
    def game_info(info_dict):

        genre_id = Genre.get_genre_id(info_dict['genre'])
        platform_id = Platform.get_platform_id(info_dict['platform'])
        game_id = Game.add_game(info_dict['title'], genre_id)
        if game_id is not None:
            Release.insert(game_id, platform_id, info_dict['release'])

    @staticmethod
    def insert(game_id, platform_id, release_date):
        cursor = connection.cursor()

        query = 'INSERT INTO release (game_id, platform_id, release_date) VALUES (%s, %s, %s)'

        cursor.execute(query, (game_id, platform_id, release_date,))
        transaction.commit_unless_managed()

    @staticmethod
    def get_game_releases(game_id):
        cursor = connection.cursor()

        query = """
            SELECT game.title, release.release_date,
            genre.name as "genre_name", platform.name as "platform_name"
            FROM release
            JOIN game ON release.game_id=game.id
            JOIN platform ON release.platform_id=platform.id
            JOIN genre ON game.genre_id=genre.id
            WHERE game_id = %s
        """

        cursor.execute(query, (game_id,))

        return dict_fetch_all(cursor)

games/views.py
from django.shortcuts import redirect, render
from django.views.decorators.http import require_POST

from games.models import Genre, Game, Release
from scrapers.metacritic import get_info

def releases(request):
    context = {'games_list': Release.select_all()}
    return render(request, 'releases.html', context)

def index(request):
    context = {'games_list': Game.select_all()}
    return render(request, 'games/index.html', context)

def game_detail(request, game_id):
    context = {
        'game_id': game_id,
        'releases': Game.game_detail(game_id),
    }
    return render(request, 'games/game_detail.html', context)

def game_add(request):
    if request.method == 'POST':
        Game.insert(
            title=request.POST['game_title'],
            genre_id=request.POST['genre_id'],
        )
        return redirect('games:index')
    else: # request.method == 'GET'
        context = {'genres': Genre.select_all()}
        return render(request, 'games/edit.html', context)

def game_edit(request, game_id):
    if request.method == 'POST':
        Game.update(game_id,
            title=request.POST['game_title'],
            genre_id=request.POST['genre_id'],
        )
        return redirect('games:index')
    else: # request.method == 'GET'
        context = {'game': Game.select(game_id), 'genres': Genre.select_all()}
        return render(request, 'games/edit.html', context)

@require_POST
def game_delete(request):
    Game.delete(request.POST['game_id'])
    return redirect('games:index')

def game_search(request):
    context = {}
    if 'title' in request.GET:
        context['games'] = Game.find(request.GET['title'])
    return render(request, 'games/search.html', context)

def game_import(request):
    if request.method == 'POST':
        for info_dict in get_info(request.POST['title'], request.POST['platform']):
            if info_dict is None:
               break
            Release.game_info(info_dict)
        return redirect('games:index')
    else:
        return render(request, 'games/import.html')

games/templates/games/detail.html
{% if game %}
<form action="{% url 'games:game_edit' game.id %}" method="post">
{% else %}
<form action="{% url 'games:game_add' %}" method="post">
{% endif %}
  Title: <input type="text" name="game_title" value="{{ game.title }}">
  <br />
  Genre:
  <select name="genre_id">
    {% for genre in genres %}
    {% ifequal game.genre_id genre.id %}
    <option value="{{ genre.id }}" selected="selected">
    {% else %}
    <option value="{{ genre.id }}">
    {% endifequal %}
      {{ genre.name }}
    </option>
    {% endfor %}
  </select>
  <br />
  <input type="submit" value="Save" />
</form>

games/templates/games/edit.html
{% extends "base.html" %}

{% block content %}
{% if game %}
<form action="{% url 'games:game_edit' game.id %}" method="post">
{% else %}
<form action="{% url 'games:game_add' %}" method="post">
{% endif %}
  {% csrf_token %}
  Title: <input type="text" name="game_title" value="{{ game.title }}">
  <br />
  Genre:
  <select name="genre_id">
    {% for genre in genres %}
    {% ifequal game.genre_id genre.id %}
    <option value="{{ genre.id }}" selected="selected">
    {% else %}
    <option value="{{ genre.id }}">
    {% endifequal %}
      {{ genre.name }}
    </option>
    {% endfor %}
  </select>
  <br />
  <input type="submit" value="Save" />
</form>
{% endblock %}

games/templates/games/game_detail.html
{% extends "base.html" %}

{% block content %}

{% if releases %}
<p>Title: {{ releases.0.title }}</p>
<p>Genre: {{ releases.0.genre_name }}</p>

<table style="border-collapse:collapse" border="1">
  <tr>
    <th>Platform</th>
    <th>Release</th>
  </tr>
{% for release in releases %}
  <tr>
    <td>{{ release.platform_name }}</td>
    <td>{{ release.release_date }}</td>
  </tr>
{% endfor%}
</table>
{% endif %}

<p><a href="{% url 'games:game_edit' game_id %}">Edit this game</a></p>

<form action="{% url 'games:game_delete' %}" method="post"
      style="display:inline">
  {% csrf_token %}
  <input type="hidden" name="game_id" value="{{ game_id }}" />
  <input type="submit" value="Delete" />
</form>
{% endblock %}

games/templates/games/import.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'games:game_import' %}" method="post">
  {% csrf_token %}
  <input type="text" name="title" placeholder="Title" /><br />
  <input type="text" name="platform" placeholder="Platform" /><br />
  <input type="submit" value="Import" /><br />
</form>
{% endblock %}

games/templates/games/index.html
{% extends "base.html" %}

{% block content %}
{% if games_list %}
<table style="border-collapse:collapse" border="1">
  <tr>
    <th>Title</th>
    <th>Genre</th>
  </tr>
  {% for game in games_list %}
  <tr>
    <td>
      <a href="{% url 'games:game_detail' game.id %}">{{ game.title }}</a>
    </td>
    <td>{{ game.genre_name }}</td>
    {% if user.is_authenticated %}
    <td>
      <form action="{% url 'accounts:add_game' %}" method="post"
            style="display:inline">
        {% csrf_token %}
        <input type="hidden" name="game_id" value="{{ game.id }}" />
        <input type="hidden" name="next" value="{{ request.path }}" />
        <input type="submit" value="Add" />
      </form>
    </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>
{% else %}
<p>Sorry, no games have been added.</p>
{% endif %}
<p><a href="{% url 'games:game_add' %}">Add new game</a></p>
<p><a href="{% url 'games:game_import' %}">Import new game</a></p>
{% endblock %}

games/templates/games/search.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'games:game_search' %}" method="get" style="display:inline">
  <input type="text" name="title" value="{{ request.GET.title }}"
         placeholder="Search for Games">
  <input type="submit" value="Search">
</form>

{% if games %}
<p>Search results:</p>
<ul>
{% for game in games %}
  <li><a href="{% url 'games:game_detail' game.id %}">{{ game.title }}</a></li>
{% endfor%}
</ul>
<p> Not here? Add it to our database </p>
<p><a href="{% url 'games:game_add' %}">Add a game</a></p>
{% elif request.GET.title %}
<p> It appears this game isn't in our database, would you like to add it? </p>
<p><a href="{% url 'games:game_add' %}">Add a game</a></p>
{% endif %}
{% endblock %}